# Welcome to Jekyll!
#

# Site settings
title: Julie Park
description: Developer & Designer
owner: Julie Park
first_published: 2017
email: julieparkdev@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: https://juliepark.me # the base hostname & protocol for your site
enforce_ssl: https://juliepark.me
social:
  twitter: https://twitter.com/juliepark
  github: https://github.com/jspark721
  linkedin-square: https://linkedin.com/in/juliepark21
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  instagram: https://instagram.com/julieeparkk
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
permalink: pretty
collections:
    portfolio:
        output: true
        permalink: /portfolio/:path/
#sass:
#  style: compressed
